### ISSUE TITLE
Extract ddoc RUNNABLE_EXAMPLE tests for phobos

### ISSUE THREAD

**Issue by ntrel** [CyberShadow/DAutoTest#7]
Extract & run the tests (like for dlang.org spec) to check the examples actually compile.
RUNNABLE_EXAMPLE seems to have been introduced to phobos in 2018 to std.exception. Recently I added it to std.regex, and I have a pull to add it to std.experimental.allocator: https://github.com/dlang/phobos/pull/8604.

In theory it could be used in druntime too, but as of now it isn't.

**Comment by CyberShadow** [comment]
Hi, this is the wrong repository to file this enhancement request.

The implementation of the machinery running the tests is in the dlang.org repository. Issues for it are tracked on Bugzilla.

The changes needed to implement this enhancement would be performed there as well. I would start by looking at `posix.mak` and `tools/dspec_tester.d`.

Hope this helps.

**Comment by ntrel** [comment]
OK, sorry. Thanks for the info. I have something implemented locally which seems promising.

**Comment by ntrel** [comment]
https://github.com/dlang/dlang.org/pull/3437
